customhost = "database.c79pgmyzgdsd.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "zhengyu2000"
customdb = "Employee"
custombucket = "tanjiapei-bucket"
customregion = "us-east-1b"
